import React from 'react'

const Home = () => {
  return (
    <div>
      <h1 style={{color:"brown",textAlign:"center"}}>This is Home Page</h1>
      <p style={{backgroundColor:"#282c"}} >
        Clita lorem takimata sea aliquyam et, aliquyam eos tempor tempor invidunt lorem stet tempor diam labore. Dolor sadipscing ipsum eirmod gubergren erat clita magna eos dolore. Tempor gubergren sanctus dolores sanctus sed lorem diam ipsum. Lorem sea consetetur invidunt eirmod, tempor et dolore sea sit eirmod et, sadipscing aliquyam stet diam ipsum sadipscing sed. Sit lorem vero erat stet dolore ut. Sit sit sanctus et dolor ea duo. Kasd invidunt amet diam accusam consetetur ut. Eirmod et ipsum rebum ea sea takimata no. Diam justo at lorem eos diam stet kasd diam, vero dolore est et eos est sit eos. Eos lorem elitr invidunt dolore ea sed aliquyam diam. Erat diam ea sed diam sadipscing eos, est sit sadipscing eos justo sit diam invidunt dolor, nonumy aliquyam clita magna ea sea lorem sanctus eirmod voluptua. Diam stet stet dolor takimata tempor dolor duo magna, vero aliquyam elitr ipsum no rebum. Voluptua duo eirmod et invidunt diam sit rebum, dolor dolores accusam sanctus dolor et ipsum justo. No lorem lorem invidunt elitr justo nonumy, tempor sadipscing et consetetur ipsum amet accusam sed dolores. Diam no ipsum magna elitr et aliquyam voluptua eos kasd. Sit sanctus eirmod ea justo. Et stet sit ipsum justo duo ipsum sit. Sit vero consetetur takimata dolores magna nonumy ea magna. Labore takimata at gubergren labore lorem sit est, takimata voluptua dolor sit dolor. Et consetetur kasd takimata est takimata. Duo clita kasd dolor dolor justo duo at. Dolor nonumy rebum at duo et sea et lorem, ea no dolore voluptua ea invidunt sea. Magna sanctus dolor amet ipsum justo amet. Sea ea et duo sit invidunt duo accusam rebum, ipsum et ea dolore diam, gubergren magna lorem sit eos et tempor dolore accusam. Sed et et ipsum aliquyam diam gubergren, vero dolore lorem et no dolor et, gubergren sed et sadipscing dolore, sanctus clita nonumy ea labore sit invidunt, dolor clita labore eos lorem et duo rebum dolor, amet et gubergren no sea. Voluptua stet stet nonumy sadipscing ut clita, eirmod elitr lorem sed et ipsum accusam kasd voluptua, sed rebum ipsum stet elitr accusam. Sanctus dolor sed stet consetetur duo amet at sed eos. Labore dolore vero justo sit ea takimata sed, ipsum nonumy tempor labore et ipsum, duo et ea et dolor sit aliquyam dolore ut. Et aliquyam labore sadipscing at. Sadipscing lorem accusam takimata clita. Justo diam sanctus nonumy sed no ut amet.
      </p><br/>
      <p style={{backgroundColor:"#282c"}} >
        Elitr ipsum lorem lorem ut vero ipsum ea. Dolor lorem dolores kasd duo amet dolor, sit rebum no sadipscing sanctus gubergren, nonumy takimata ut sadipscing accusam et diam ut. Accusam sed et gubergren dolor accusam amet, labore amet dolor elitr sanctus amet takimata, dolores sanctus invidunt nonumy est ipsum et. Ipsum et dolor diam sed ut vero, clita ea dolores amet kasd. Amet takimata sed duo elitr duo duo, voluptua stet magna amet sed voluptua eirmod lorem sanctus consetetur, dolor sea lorem takimata dolor amet dolore amet, vero stet accusam takimata clita labore, amet no gubergren ea takimata sed eirmod sit eos, elitr magna justo erat sadipscing sit aliquyam sadipscing dolor. Sadipscing tempor amet et rebum. Lorem ipsum diam tempor kasd diam elitr elitr sanctus. Takimata at labore at voluptua et. Eirmod sit erat elitr invidunt sit clita sed et sed. No ut diam invidunt no dolores vero labore dolor, erat invidunt sanctus sed ut kasd. Magna sit sadipscing diam lorem amet sit. Rebum ut est no dolor, et erat dolores gubergren sea invidunt consetetur et, at lorem et sea takimata stet sit ipsum dolor. Nonumy elitr rebum et ipsum sea sanctus nonumy sed. Consetetur eirmod ipsum erat invidunt nonumy.
      </p>

    </div>
  )
}

export default Home
